version: '3.4'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:

  ### Workspace ############################################
  workspace:
    build:
      context: ./workspace
      network: host
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    env_file: .env
    volumes:
      - ../:/var/www:cached
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2375
    depends_on:
      - redis
      - mysql
    networks:
      - frontend
      - backend
    command: [
      "wait-for-it.sh", "mysql:3306", "--",
      "wait-for-it.sh", "redis:6379", "--",
      "zsh"
    ]

  ### PHP-FPM ##############################################
  php-fpm:
    build:
      context: ./php-fpm
      network: host
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./php-fpm/php7.4.ini:/usr/local/etc/php/php.ini
      - ../:/var/www:cached
    expose:
      - "9000"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2375
    depends_on:
      - redis
      - mysql
    networks:
      - backend

  ### NGINX Server ##########################################
  nginx:
    build:
      context: ./nginx
      network: host
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ../:/var/www:cached
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

### PHP Worker ############################################
  php-worker:
    build:
      context: ./php-worker
      network: host
    volumes:
      - ../:/opt/society6:cached
      - ./php-worker/supervisord.d:/etc/supervisord.d
    ports:
      - "9001:9001"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    depends_on:
      - redis
      - mysql
    networks:
      - backend

  ### MySQL #################################################
  mysql:
    image: mysql:5.7.27
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
    command: ['mysqld', '--character-set-server=latin1', '--collation-server=latin1_swedish_ci', '--max_allowed_packet=32505856']

### Redis ################################################
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
    entrypoint: redis-server --appendonly yes
    restart: always
